version: '3.7'
services:

  mysql-user:
    container_name: mysql-user
    image: mysql:8.0
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-service
    volumes:
      - ./user-service-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

